# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd9eb2dea8809fc3a1fb2e03e0f086d03967df4990f6808855887eb361993eb6256eb9fa05ca35772e3f888c4f261ad88ab1a151a3d1e8b085b70d60a3aa4c25

test:
  secret_key_base: 8a88763d8d4404d953c3682614fd3b6e685a58ba4ac850535d8732ca336b40b035c148b30302ffe591efd17e5a6d2141ecb513a1583b70cbc247c74eee22c957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
